<a href="https://colab.research.google.com/github/ianbennett41430/ICP3/blob/main/ICP3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Using NumPy create random vector of size 15 having only Integers in the range 1-20.

In [9]:
from numpy.core.multiarray import ndarray
import numpy as np
import pandas as pd
import random
import matplotlib

print("The original array is:")
array1 = np.arange(15)
print(array1)
#Reshape the array to 3 by 5.
print("The reshaped 3x5 array is:")
array2 = array1.reshape(3, 5)
print(array2)
#Print array shape.
row,col = array2.shape
print("The size of the matrix is a",row,"by", col)
#Replace the max in each row by 0.
array2 = np.max(array2, axis = 1)
print(array2)

The original array is:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
The reshaped 3x5 array is:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
The size of the matrix is a 3 by 5
[ 4  9 14]


2. Create a 2-dimensional array of size 4 x 3 (composed of 4-byte integer elements), also print the shape,
type, and data type of the array.

In [8]:
import numpy as np
arr = (np.arange(12).reshape(4,3), np.int32)
print(arr)
print(type(arr), np.shape(arr))



(array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]]), <class 'numpy.int32'>)
<class 'tuple'> (2,)


/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py:2009: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  result = asarray(a).shape


3. Compute the sum of the diagonal element of a given array.

In [ ]:
arr3 = np.arange(6).reshape(2,3)
print(arr3)
result =  np.trace(arr3)
print("The sum of the diagonal is:", result)

[[0 1 2]
 [3 4 5]]
The sum of the diagonal is: 4


4. Write a NumPy code:

In [7]:
import numpy as np
import array as ar

#To create an array of odd and even numbers between 10 to 70.
arr4 = np.arange(10,71)
print(arr4)
#To perform at-least three element-wise mathematical operations using two arrays of the same size.
arr5 = np.arange(6).reshape(2,3)
arr6 = np.arange(6).reshape(2,3)
print(np.add(arr5,arr6))
print(np.subtract(arr5,arr6))
print(np.multiply(arr5,arr6))
#To sort a given array by row and column in ascending order.
arr7 = np.array([[5.54, 3.38, 7.99],
 [3.54, 4.38, 6.99],
 [1.54, 2.39, 9.29]])
print("The starting array is:", arr7)
np.sort(arr7)
np.sort(arr7,axis=1)
print("The sorted array is:",np.sort(arr7,axis=0))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70]
[[ 0  2  4]
 [ 6  8 10]]
[[0 0 0]
 [0 0 0]]
[[ 0  1  4]
 [ 9 16 25]]
The starting array is: [[5.54 3.38 7.99]
 [3.54 4.38 6.99]
 [1.54 2.39 9.29]]
The sorted array is: [[1.54 2.39 6.99]
 [3.54 3.38 7.99]
 [5.54 4.38 9.29]]


5. Declare an array given below using NumPy and find missing data by returning Boolean output
(True/False).

In [1]:
import numpy as np
import array as ar

arr8 = np.array([[4, 2, np.nan, 1],
[11, 12, 14, 9],
 [5, np.nan, 1, np.nan]])
print(arr8)
print(np.isnan(arr8))


[[ 4.  2. nan  1.]
 [11. 12. 14.  9.]
 [ 5. nan  1. nan]]
[[False False  True False]
 [False False False False]
 [False  True False  True]]
